### ISSUE TITLE
Inactive Members should be pruned after a configurable inactive time. 

### ISSUE THREAD

**Issue by lonnieezell** [lonnieezell/forum-example#121]
When a user has been inactive for an extended length of time (measure in years) the account and all data should be removed, after a couple of warning emails. 

- new Tasks that run weekly
  - notify users 30 days from deletion date
  - notify users 7 days from deletion date
  - notify users 3 days from deletion date
  - delete users  and their data that have been inactive for the set amount of months
- config item to specify how many months should be considered for deletion

EDIT: Maybe they should just be soft-deleted? That protects the old account but still allows it to be restored somehow? Open for discussion on this. 

reference: https://blog.google/technology/safety-security/updating-our-inactive-account-policies/

**Comment by michalsn** [comment]
I've read the article, but I'm not entirely convinced that this is a good idea. Forums are a pretty specific use case. People come and go, but the content created can be very useful for years to come.

The first example that comes to my mind. A developer ran 1 or 2 projects with CodeIgniter, during this time he initiated some pretty popular/useful discussions. Years later, they are still popular. He has moved on and is now a Golang developer. He doesn't care about forum, so he probably won't click the link in the email.

Maybe we could enable 2FA (e-mail) for users who have been inactive for a long time? That would reduce the possibility of using leaked/old passwords by someone.

**Comment by lonnieezell** [comment]
> Maybe we could enable 2FA (e-mail) for users who have been inactive for a long time? That would reduce the possibility of using leaked/old passwords by someone.

I like that. 

Good points on the rest of it. I think forcing 2FA in that case would work well.
