### ISSUE TITLE
Visitors should be able to see members of the site.

### ISSUE THREAD

**Issue by lonnieezell** [lonnieezell/forum-example#13]
A new "Members" page should be present that displays a paginated list of all users within the system. 

They should be presented with a search for this page only that searches and filters the list of users by the following criteria: 
- username
- role (admin, moderator especially)
- new users (with 1 or less posts)
- country

You should be able to sort the list of users by : 
- number of posts
- username, asc
- most recent posts, desc

**Comment by michalsn** [comment]
There is no option to assign the issue.

 I'll try to play with it - it seems relatively simple to start with.

**Comment by lonnieezell** [comment]
@michalsn I've sent you an invite as a collaborator if you wish. I'll go ahead an assign this one to you. 

Thanks!
