### ISSUE TITLE
Bug: Discussions are not viewable when user is not logged in. 

### ISSUE THREAD

**Issue by lonnieezell** [lonnieezell/forum-example#225]
@michalsn  there is an issue with the permissions checks on categories. 

Part of the reason I found is that even though the data seeder is setting `null` as the permission for the category, when it's pulled back out it is `[0 => `N;]`. It seems to be an issue at the framework level. I'm surprised no one has run across this yet.

**Comment by michalsn** [comment]
I remember that I changed the DB schema when I added permission checking in categories. So that might be the reason. I edited the old migration file.

If the `categories.permissions` field is set to `null`, it should be handled fine, since we allow the `null` value when we cast it in Entity.

I just created all the tables from scratch and ran the seeder. Everything is fine.

You may also check if there is no cache since I cache available categories: `category-permissions` in the cache folder.

**Comment by lonnieezell** [comment]
Weird. I emptied the database and pulled down all new code so it was basically a fresh install last night and still ran into those problems. Couldn't remember if I did the database so I wiped it this morning to try and the same thing. 

I'm using MySQL 8.1.0. All empty `permissions` field on the database have `N;` instead of simply being empty. Figured that was from the casting but haven't dug that deep yet. Started to do some fixes for it then figured you'd probably know what happened so started this thread :) I can dig in more tonight.

**Comment by michalsn** [comment]
> Couldn't remember if I did the database so I wiped it this morning to try and the same thing.

That's really strange. I'm on MySQL 8.0.19. I remember we had this `N;` at the beginning but I wasn't able to cast it to anything that would make sense so I changed it to the "native" `null` value.

In my case, after running migrations + seeding, the `permissions` field is set to `null` (except for the "Operations" category).

[Factory](https://github.com/lonnieezell/forum-example/blob/develop/app/Models/Factories/CategoryFactory.php#L24) sets `permissions` to `null` by default. [Entity](https://github.com/lonnieezell/forum-example/blob/develop/app/Entities/Category.php#L19) also allows the `null` value.

**Comment by lonnieezell** [comment]
Turns out it's not a problem. It was a mixture of caching and old data that was doing weird stuff. I got it resolved locally, though. Closing.
