### ISSUE TITLE
Force2FA setting isn't forcing 2FA after login

### ISSUE THREAD

**Issue by lonnieezell** [lonnieezell/forum-example#255]
The value appears to be saved correctly with settings but doesn't seem to be used by Shield. 

I only realized this just after merging the user settings branch in. 

Should force a 2fa check after login when checked.

**Comment by michalsn** [comment]
Well, that's gonna be a tough one.

I modified the way 2FA works in the `TwoFactorAuthEmail` class so that we can only use it if the user enables it or if the account has not been used for 1 year.

I don't see a way to force this for everyone without using an extra variable.

**Comment by lonnieezell** [comment]
Oh, that's right. I forgot about that. Then we should remove that setting from the Users Settings page and call it good, it sounds like.

**Comment by michalsn** [comment]
We might fix it by using `Email2FA` when the 2FA is enabled, and `TwoFactorAuthEmail` when 2FA is disabled. It probably should work.
