### ISSUE TITLE
Logged in users should be able to create a new post

### ISSUE THREAD

**Issue by lonnieezell** [lonnieezell/forum-example#9]
A new button should be present in the sidebar titled "Start a Discussion". This is only available when the user is logged in. When clicked, this should present a form for the user to start a new discussion. 

The form should appear on a new page. 

The following fields should be available: 

- Title
- Message - in a Markdown/BBCode-supporting editor 
- Save button

> Note: new posts should support Markdown, but old posts that we would import would need to support BBCode. Viewing a post already supports both languages.

**Comment by michalsn** [comment]
Any suggestions regarding markdown/bbcode editor? Seems like we will have to use two different ones.

**Comment by datamweb** [comment]
I've done a little work on this, but I'd love for you to do it.
I used [tiny](https://www.tiny.cloud/) in my implementation, however there are some limitations that don't seem to be useful. I tried to find a better one but failed.

![Screenshot 2023-09-04 225507](https://github.com/lonnieezell/forum-example/assets/9530214/e8196aef-3ab7-4d75-9329-2ffa53b199bf)

**Comment by datamweb** [comment]
Currently, the CI forum uses the following package.
https://github.com/samclarke/SCEditor

**Comment by lonnieezell** [comment]
I would make the priority here Markdown, personally. My original thoughts were that all new posts would be Markdown, and the BBCode support was primarily there to support the thousands of posts that would be imported. I don't see very many BBCode posts at all needing to be edited after the switch, so I think it's fine if that experience is sub-par personally. 

As for recommendations, it's been awhile since I was looking, but I had [this page](https://ourcodeworld.com/articles/read/359/top-7-best-markdown-editors-javascript-and-jquery-plugins) bookmarked to research into a bit more. Also [EasyMDE](https://github.com/Ionaru/easy-markdown-editor). Years ago I used [MarkitUp](https://markitup.jaysalvat.com/home/) but that requires JQuery to be pulled in and not sure we want to go down that path if we don't need to. 

My goal for the editor was something that was simple and clean, but could support GitHub flavored markdown and be easily extendable.

**Comment by michalsn** [comment]
I'll try to do some more research today on what options we have. But definitely, jQuery is out.

**Comment by michalsn** [comment]
It seems to me that to simplify things at the beginning, we should just forget about the editor for bbcode.

Old bbcode entries after import should only be available for editing by moderation and they can do without an editor. This way we can focus on Markdown only.

**Comment by michalsn** [comment]
I think we can give EasyMDE a try... I also found:
* https://github.com/nhn/tui.editor - very heavy but feature-rich
* https://github.com/github/markdown-toolbar-element - quite ascetic

Other than that, there are not that many possibilities that aren't older than ~5 years.

Anyway, we can always make a switch later.
